# Project
endless-charset: UTF-8 # 字符集
endless-date-pattern: yyyy-MM-dd # 日期格式
endless-date-time-pattern: yyyy-MM-dd HH:mm:ss:SSS # 日期时间格式
endless-data-center-id: 1 # 数据中心 ID
endless-worker-id: 1 # 工作节点 ID
endless-sidecar-mesh-mode-enabled: false # 是否启用 Service Mesh 模式
endless-sidecar-host: 127.0.0.1 # 边车主机地址
endless-sidecar-port: 60005 # 边车端口
# Server
server-port: 60005 # 服务端口
# Undertow
undertow-worker-threads: 100 # 最大工作线程数
undertow-io-threads: 8 # IO 线程数
undertow-server-options-idle-timeout: 20000 # 连接超时时间（毫秒）
undertow-server-options-so-backlog: 100 # 请求队列长度
undertow-max-http-header-size: 8192 # 最大请求头大小
undertow-buffer-cache-size: 8192 # Servlet缓冲区大小
# Datasource
datasource-driver-class-name: org.sqlite.JDBC # 数据库驱动类
datasource-url: jdbc:sqlite:file:data/demo.db # 数据库连接 URL
datasource-username: "" # 数据库用户名
datasource-password: "" # 数据库密码
#Logging
logging-config: file:config/log4j2-dev.xml
