#Server
server-port: 60500
#Tomcat
tomcat-connection-timeout: 20000 # 设置连接超时时间，单位为毫秒
tomcat-max-threads: 200 # 设置最大线程数
tomcat-min-spare-threads: 10 # 设置最小闲置线程数
tomcat-accept-count: 100 # 设置最大请求队列数
tomcat-max-http-header-size: 8192 # 设置最大 HTTP 请求头大小，单位为字节
tomcat-uri-encoding: UTF-8 # 设置 URI 编码格式
#Logging
logging-config: file:config/log4j2-dev.xml
