endless:
  charset: UTF-8
  date-pattern: yyyy-MM-dd
  date-time-pattern: yyyy-MM-dd HH:mm:ss:SSS
  data-center-id: 1
  worker-id: 1
  sidecar:
    host: 127.0.0.1
    port: 60005
#------------------------Server-------------------------
server:
  port: ${server-port} # 服务端口
  tomcat:
    connection-timeout: ${tomcat-connection-timeout} # 设置连接超时时间，单位为毫秒
    max-threads: ${tomcat-max-threads} # 设置最大线程数
    min-spare-threads: ${tomcat-min-spare-threads} # 设置最小闲置线程数
    accept-count: ${tomcat-accept-count} # 设置最大请求队列数
    max-http-header-size: ${tomcat-max-http-header-size} # 设置最大 HTTP 请求头大小，单位为字节
    uri-encoding: ${tomcat-uri-encoding} # 设置 URI 编码格式
  error:
    whitelabel:
      enabled: false # 禁用默认错误页面
spring:
  application:
    name: endless-ddd-sidecar
  profiles:
    active: dev
  freemarker:
    enabled: true # 启用 Freemarker 模板引擎
    template-loader-path: file:templates/freemarker/ # Freemarker 模板路径
    suffix: .ftl # Freemarker 模板后缀
    check-template-location: false #
  mvc:
    throw-exception-if-no-handler-found: true # 未找到请求处理器时，抛出异常
  datasource:
    driver-class-name: ${datasource-driver-class-name}  # 设置数据库驱动类
    url: ${datasource-url} # 数据库连接 URL
    username: ${datasource-username}  # 数据库用户名
    password: ${datasource-password}  # 数据库密码
#------------------------Logging------------------------
logging:
  config: ${logging-config}
log4j2:
  enableScript: true
#-----------------------Actuator------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    base-path: /actuator
